# Generated by Django 5.2.1 on 2025-05-15 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinnyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'binny_library',
            },
        ),
        migrations.CreateModel(
            name='BinnyTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binny_type', models.CharField(choices=[('cup', 'Cup'), ('bottle', 'Bottle'), ('container', 'Container')], max_length=100)),
            ],
            options={
                'db_table': 'binny_texture',
            },
        ),
        migrations.CreateModel(
            name='BinnyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'binny_user',
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_clean', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('binny_type', models.CharField(choices=[('cup', 'Cup'), ('bottle', 'Bottle'), ('container', 'Container')], max_length=100)),
                ('how_to_recycle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detection_result',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255, null=True)),
                ('blob', models.BinaryField()),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Binny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binny_type', models.CharField(choices=[('cup', 'Cup'), ('bottle', 'Bottle'), ('container', 'Container')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('xp', models.BigIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.binnycollection')),
            ],
            options={
                'db_table': 'binny_buddy',
            },
        ),
        migrations.AddField(
            model_name='binnycollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collection_set', related_query_name='collection', to='core.binnyuser'),
        ),
        migrations.CreateModel(
            name='RewardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_binny_created', models.BooleanField(default=None, null=True)),
                ('earned_xp', models.BigIntegerField(default=None, null=True)),
                ('binny', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.binny')),
                ('detection_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.detectionresult')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.binnyuser')),
            ],
            options={
                'db_table': 'reward_history',
            },
        ),
    ]
