# Generated by Django 5.2.1 on 2025-05-11 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinnyLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'binny_library',
            },
        ),
        migrations.CreateModel(
            name='BinnyTexture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binny_type', models.CharField(choices=[('CUP', 'Cup'), ('BOTTLE', 'Bottle'), ('CONTAINER', 'Container')], max_length=100)),
            ],
            options={
                'db_table': 'binny_texture',
            },
        ),
        migrations.CreateModel(
            name='BinnyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'binny_user',
            },
        ),
        migrations.CreateModel(
            name='Binny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binny_type', models.CharField(choices=[('CUP', 'Cup'), ('BOTTLE', 'Bottle'), ('CONTAINER', 'Container')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.binnylibrary')),
            ],
            options={
                'db_table': 'binny_buddy',
            },
        ),
        migrations.AddField(
            model_name='binnylibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.binnyuser'),
        ),
    ]
