# Generated by Django 5.2.1 on 2025-05-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binny',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.binnycollection'),
        ),
        migrations.AlterField(
            model_name='binnycollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_set', related_query_name='collection', to='core.binnyuser'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.binnyuser'),
        ),
        migrations.AlterField(
            model_name='rewardhistory',
            name='binny',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.binny'),
        ),
        migrations.AlterField(
            model_name='rewardhistory',
            name='detection_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.detectionresult'),
        ),
        migrations.AlterField(
            model_name='rewardhistory',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
        migrations.AlterField(
            model_name='rewardhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.binnyuser'),
        ),
    ]
